name: CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
  workflow_dispatch:

jobs:
  build-test-format:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '25'

      # - name: Grant execute permission for gradlew
        # run: chmod +x ./gradlew

      - name: Build project
        run: ./gradlew build

      - name: Run tests
        run: ./gradlew test

      - name: Check formatting
        run: ./gradlew spotlessCheck
